In [9]:
import numpy as np
print(np.__version__)

2.3.5


In [10]:
list=[1,2,3,4]
print(list)
list*=2
print(list)
print()

data=[1,2,3,4]
print(data)
array=np.array(data)
array*=2
print(array)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]

[1, 2, 3, 4]
[2 4 6 8]


In [24]:
#number of dimensions

array=np.array([['A','B'],['D','F'],['E','Z']]) #2D
array=np.array('A') #0D
array=np.array(['A','B']) #1D
array=np.array([[['A','B'],['D','F'],['E','Z']],
               [['G','H'],['I','J'],['L','M']],
               [['A','R'],['Q','P'],['O','N']]]) #3D
print(array.ndim)
print(array.shape) #3layers, 3rows and 2cols in each
print(array[0][1][0]) #chain indexing
print(array[0,1,0]) #multidimensional indexing


3
(3, 3, 2)
D
D


In [29]:
array = np.array([
    [['A','B','C'],['D','E','F'],['G','H','I']],
    [['J','K','L'],['M','N','O'],['P','Q','R']],
    [['S','T','U'],['V','W','X'],['Y','Z','']]  ])
print(array.shape)
word=array[0,2,1]+array[0,2,2]
print(word)

(3, 3, 3)
HI


In [42]:
#slicing
array=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16] ])
print(array[-1]) #last one
print(array[-2])
print(array[0:3]) #start:end:step
print()
print(array[0:4:2])
print()
print(array[::-1]) #reverse
print()
print(array[0,0]) #0th row, 0th column
print()
print(array[:,0]) #1st element of all rows
print()
print(array[:,0:3]) #all rows, first 3cols
print()
print(array[:,::-1]) #all rows, reversed cols

[13 14 15 16]
[ 9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 9 10 11 12]]

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

1

[ 1  5  9 13]

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [44]:
#scalar maths
array=np.array([1,2,3])
print(array+2)
print(array**2)



[3 4 5]
[1 4 9]


In [59]:
#vectorised math fncs
array=np.array([1.4,4.6,9.5])
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array)) #round-down
print(np.ceil(array)) #round-down
print(np.pi)
print()

radi=np.array([1,2,3])
print(np.pi*(radi**2)) #area of a circle
print()

array1=np.array([1,2,3]) #element-wise arithematics
array2=np.array([4,5,6])
print(array1+array2)
print()

scores=np.array([91,55,100,73,82,64])
print(scores==100)
print(scores>=60)
scores[scores<60]=0
print(scores)


[1.18321596 2.14476106 3.082207  ]
[ 1.  5. 10.]
[1. 4. 9.]
[ 2.  5. 10.]
3.141592653589793

[ 3.14159265 12.56637061 28.27433388]

[5 7 9]

[False False  True False False False]
[ True False  True  True  True  True]
[ 91   0 100  73  82  64]


In [63]:
#broadcasting allows numpy to perform operations on arrays w diff shapes by virtually expanding dimensions
#so that the smaller array will match the bigger array
#rules: dimensions have same size or one of the dimensions has size of 1
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)

print(array1*array2)
print()

#multiplication table
a1=np.array([[1,2,3,4,5,6,7,8,9,10]])
a2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(a1.shape)
print(a2.shape)
print(a1*a2)


(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [66]:
#aggregate fncs= summarize data and return a single value
array=np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print(np.sum(array))
print(np.std(array))
print(np.var(array))
print(np.mean(array))
print(np.max(array))
print(np.argmin(array))#position of the min value
print(np.sum(array,axis=0)) #sum across columns
print(np.sum(array,axis=1)) #sum across rows

55
2.8722813232690143
8.25
5.5
10
0
[ 7  9 11 13 15]
[15 40]


In [75]:
#filtering
ages=np.array([[21,17,19,20,16,30,18,65],
               [39,22,15,99,18,19,20,21]])
teenagers=ages[ages<18]
print(teenagers)
adults=ages[(ages>=18) & (ages<65)]
print(adults)
seniors=ages[ages>=65]
print(seniors)
evens=ages[ages%2==0]
print(evens)
odds=ages[ages%2!=0]
print(odds)
print()

adults2=np.where(ages>=18,ages,np.nan) #condition,fromw which data,replace with what
print(adults2)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]

[[21. nan 19. 20. nan 30. 18. 65.]
 [39. 22. nan 99. 18. 19. 20. 21.]]


In [103]:
#random number generator
random=np.random.default_rng()
random2=np.random.default_rng(seed=1) #so that the random no generated once will be same for how many ever times you run it
print(random2.integers(1,100))
print(random.integers(1,7))
print(random.integers(low=1,high=101,size=3)) #low and high chumma for readability
print()

print(random.integers(low=1,high=101,size=(3,2))) #3rows and 2cols
print()

print(np.random.uniform()) #uniform chance for all numbers bw 0 and 1
print(np.random.uniform(low=1,high=2,size=(3,2)))
print()

np.random.seed(seed=1)
print(np.random.uniform(low=1,high=2,size=(3,2)))
print()
print()

print("shuffling of array")
array=np.array([1,2,3,4,5])
random.shuffle(array)
print(array)
print()

fruits=np.array(['apple','banana','orange','kiwi'])
x=random.choice(fruits,size=3)
y=random.choice(fruits,size=(3,2))
print(x)
print(y)


47
1
[84 97 76]

[[54 16]
 [78 10]
 [44  2]]

0.1862602113776709
[[1.34556073 1.39676747]
 [1.53881673 1.41919451]
 [1.6852195  1.20445225]]

[[1.417022   1.72032449]
 [1.00011437 1.30233257]
 [1.14675589 1.09233859]]


shuffling of array
[2 5 1 4 3]

['banana' 'banana' 'kiwi']
[['banana' 'kiwi']
 ['kiwi' 'banana']
 ['banana' 'orange']]
